language: node_js
dist: trusty
sudo: false
node_js: stable
install:
  - export PATH=$HOME/purescript:$HOME/node_modules/bin:$PATH
  - PURESCRIPT_VERSION=0.11.7
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v${PURESCRIPT_VERSION}/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install bower
script:
  - ./test.sh
